export const Api = [
  {
    id: 1,
    model: "Boeing 747",
    manufacturer: "Boeing",
    year: 1968,
    capacity: 416,
    range_km: 10380,
    type: "commercial",
  },
  {
    id: 2,
    model: "Airbus A380",
    manufacturer: "Airbus",
    year: 2005,
    capacity: 555,
    range_km: 15700,
    type: "commercial",
  },
  {
    id: 3,
    model: "Cessna 172",
    manufacturer: "Cessna",
    year: 1956,
    capacity: 4,
    range_km: 1600,
    type: "general aviation",
  },
  {
    id: 4,
    model: "Lockheed Martin F-22",
    manufacturer: "Lockheed Martin",
    year: 1997,
    capacity: 1,
    range_km: 2960,
    type: "military",
  },
  {
    id: 5,
    model: "Embraer E195",
    manufacturer: "Embraer",
    year: 2004,
    capacity: 120,
    range_km: 4000,
    type: "regional",
  },
  {
    id: 6,
    model: "Boeing 777",
    manufacturer: "Boeing",
    year: 1994,
    capacity: 396,
    range_km: 9400,
    type: "commercial",
  },
  {
    id: 7,
    model: "Airbus A320",
    manufacturer: "Airbus",
    year: 1988,
    capacity: 150,
    range_km: 6100,
    type: "commercial",
  },
  {
    id: 8,
    model: "Bombardier Q400",
    manufacturer: "Bombardier",
    year: 2000,
    capacity: 78,
    range_km: 2500,
    type: "regional",
  },
  {
    id: 9,
    model: "Boeing 787",
    manufacturer: "Boeing",
    year: 2011,
    capacity: 242,
    range_km: 14800,
    type: "commercial",
  },
  {
    id: 10,
    model: "McDonnell Douglas MD-80",
    manufacturer: "McDonnell Douglas",
    year: 1980,
    capacity: 150,
    range_km: 3000,
    type: "commercial",
  },
  {
    id: 11,
    model: "Lockheed C-130 Hercules",
    manufacturer: "Lockheed Martin",
    year: 1956,
    capacity: 92,
    range_km: 5000,
    type: "military",
  },
  {
    id: 12,
    model: "Piper PA-28",
    manufacturer: "Piper Aircraft",
    year: 1960,
    capacity: 4,
    range_km: 800,
    type: "general aviation",
  },
  {
    id: 13,
    model: "Boeing 737",
    manufacturer: "Boeing",
    year: 1968,
    capacity: 200,
    range_km: 5800,
    type: "commercial",
  },
  {
    id: 14,
    model: "Airbus A350",
    manufacturer: "Airbus",
    year: 2013,
    capacity: 410,
    range_km: 15000,
    type: "commercial",
  },
  {
    id: 15,
    model: "Cirrus SR22",
    manufacturer: "Cirrus Aircraft",
    year: 2001,
    capacity: 4,
    range_km: 1600,
    type: "general aviation",
  },
  {
    id: 16,
    model: "Boeing 767",
    manufacturer: "Boeing",
    year: 1982,
    capacity: 216,
    range_km: 11000,
    type: "commercial",
  },
  {
    id: 17,
    model: "Airbus A220",
    manufacturer: "Airbus",
    year: 2016,
    capacity: 120,
    range_km: 6000,
    type: "commercial",
  },
  {
    id: 18,
    model: "McDonnell Douglas DC-10",
    manufacturer: "McDonnell Douglas",
    year: 1970,
    capacity: 270,
    range_km: 10300,
    type: "commercial",
  },
  {
    id: 19,
    model: "Northrop F-5",
    manufacturer: "Northrop",
    year: 1962,
    capacity: 2,
    range_km: 2500,
    type: "military",
  },
  {
    id: 20,
    model: "Sukhoi Superjet 100",
    manufacturer: "Sukhoi",
    year: 2008,
    capacity: 108,
    range_km: 3000,
    type: "regional",
  },
  {
    id: 21,
    model: "Dassault Falcon 7X",
    manufacturer: "Dassault Aviation",
    year: 2005,
    capacity: 14,
    range_km: 11000,
    type: "business",
  },
  {
    id: 22,
    model: "Boeing 757",
    manufacturer: "Boeing",
    year: 1982,
    capacity: 200,
    range_km: 6000,
    type: "commercial",
  },
  {
    id: 23,
    model: "Piper PA-32",
    manufacturer: "Piper Aircraft",
    year: 1965,
    capacity: 6,
    range_km: 1300,
    type: "general aviation",
  },
  {
    id: 24,
    model: "Gulfstream G650",
    manufacturer: "Gulfstream Aerospace",
    year: 2008,
    capacity: 19,
    range_km: 13000,
    type: "business",
  },
  {
    id: 25,
    model: "Airbus A321",
    manufacturer: "Airbus",
    year: 1994,
    capacity: 240,
    range_km: 7400,
    type: "commercial",
  },
  {
    id: 26,
    model: "Boeing 737 MAX",
    manufacturer: "Boeing",
    year: 2016,
    capacity: 220,
    range_km: 6400,
    type: "commercial",
  },
  {
    id: 27,
    model: "Fokker 100",
    manufacturer: "Fokker",
    year: 1986,
    capacity: 100,
    range_km: 3000,
    type: "regional",
  },
  {
    id: 28,
    model: "Embraer ERJ-145",
    manufacturer: "Embraer",
    year: 1995,
    capacity: 50,
    range_km: 2500,
    type: "regional",
  },
  {
    id: 29,
    model: "Beechcraft Baron",
    manufacturer: "Beechcraft",
    year: 1961,
    capacity: 6,
    range_km: 1700,
    type: "general aviation",
  },
  {
    id: 30,
    model: "Airbus A330",
    manufacturer: "Airbus",
    year: 1992,
    capacity: 300,
    range_km: 13000,
    type: "commercial",
  },
  {
    id: 31,
    model: "Boeing 717",
    manufacturer: "Boeing",
    year: 1998,
    capacity: 134,
    range_km: 6100,
    type: "commercial",
  },
  {
    id: 32,
    model: "Lockheed Martin F-35",
    manufacturer: "Lockheed Martin",
    year: 2006,
    capacity: 1,
    range_km: 2200,
    type: "military",
  },
  {
    id: 33,
    model: "Airbus A310",
    manufacturer: "Airbus",
    year: 1982,
    capacity: 280,
    range_km: 9000,
    type: "commercial",
  },
  {
    id: 34,
    model: "Boeing 787 Dreamliner",
    manufacturer: "Boeing",
    year: 2011,
    capacity: 242,
    range_km: 14800,
    type: "commercial",
  },
  {
    id: 35,
    model: "Lockheed Martin P-3 Orion",
    manufacturer: "Lockheed Martin",
    year: 1961,
    capacity: 12,
    range_km: 7000,
    type: "military",
  },
  {
    id: 36,
    model: "Cessna Citation X",
    manufacturer: "Cessna",
    year: 1996,
    capacity: 8,
    range_km: 6000,
    type: "business",
  },
  {
    id: 37,
    model: "Boeing 707",
    manufacturer: "Boeing",
    year: 1958,
    capacity: 140,
    range_km: 9300,
    type: "commercial",
  },
  {
    id: 38,
    model: "Airbus A350-1000",
    manufacturer: "Airbus",
    year: 2016,
    capacity: 410,
    range_km: 16000,
    type: "commercial",
  },
];
